### ISSUE TITLE
    session_id = get_report_ctx().session_id AttributeError: 'NoneType' object has no attribute 'session_id'

### ISSUE THREAD

**Issue by foxxcrypto** [Cawinchan/Streamlit-Multi-Page-Stock-Dashboard#1]
Hi, i am trying your code but i get the following error:

"Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.5\plugins\python-ce\helpers\pydev\pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.5\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/DEVELOP/PYTHON/streamlit-dashboards/Streamlit-Multi-Page-Stock-Dashboard-master/main_stock_app.py", line 183, in <module>
    main("testing_dashboard")
  File "C:/DEVELOP/PYTHON/streamlit-dashboards/Streamlit-Multi-Page-Stock-Dashboard-master/main_stock_app.py", line 65, in main
    state = _get_state()
  File "C:/DEVELOP/PYTHON/streamlit-dashboards/Streamlit-Multi-Page-Stock-Dashboard-master/main_stock_app.py", line 174, in _get_state
    session = _get_session()
  File "C:/DEVELOP/PYTHON/streamlit-dashboards/Streamlit-Multi-Page-Stock-Dashboard-master/main_stock_app.py", line 164, **in _get_session
    session_id = get_report_ctx().session_id
AttributeError: 'NoneType' object has no attribute 'session_id'**
![main_stock_app_error](https://user-images.githubusercontent.com/48240112/125298242-432aaf80-e328-11eb-947a-12d275024b7b.PNG)

**Comment by Cawinchan** [comment]
Hello @foxxcrypto! You have to use $ _streamlit run main_stock_app.py_ in order to run the streamlit app, you can't use python or run the python file in your IDE

![image](https://user-images.githubusercontent.com/33630146/125338147-697d3900-e382-11eb-9e36-bbd0b1f334ac.png)
